name: flutter_bullet_list
description: A new Flutter Plugin for ordered and unordered lists
version: 0.0.1
homepage: https://github.com/R3-V3NG3R/flutter_bullet_list

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

